ERROR - 2022-11-27 21:35:57 --> mysqli_sql_exception: Unknown column 'user_image email;' in 'field list' in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`....', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\app\Controllers\Admin.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(907): App\Controllers\Admin->detail('4')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-11-27 21:35:57 --> Unknown column 'user_image email;' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = \'4\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = \'4\'')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = \'4\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = :users.id:', [...], false)
 5 APPPATH\Controllers\Admin.php(40): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Admin->detail('4')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-27 21:36:56 --> mysqli_sql_exception: Unknown column 'email;' in 'field list' in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`....', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\app\Controllers\Admin.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(907): App\Controllers\Admin->detail('4')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-11-27 21:36:56 --> Unknown column 'email;' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image`, `email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = \'4\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image`, `email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = \'4\'')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image`, `email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = \'4\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id` as `userid`, `username`, `fullname`, `user_image`, `email;` `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` =`auth_groups_users`.`group_id`
WHERE `users`.`id` = :users.id:', [...], false)
 5 APPPATH\Controllers\Admin.php(40): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Admin->detail('4')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-27 22:12:25 --> syntax error, unexpected 'if' (T_IF)
in APPPATH\Views\admin\detail.php on line 42.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('admin/detail', [], true)
 3 APPPATH\Controllers\Admin.php(47): view('admin/detail', [...])
 4 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Admin->detail('4')
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-27 22:43:00 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-27 22:43:00 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `users`.`deleted_at` IS NULL
AND `users`.`id` = :users.id:', [...], false)
 3 SYSTEMPATH\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
 5 VENDORPATH\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
 7 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 8 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-27 22:43:04 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-27 22:43:04 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `users`.`deleted_at` IS NULL
AND `users`.`id` = :users.id:', [...], false)
 3 SYSTEMPATH\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
 5 VENDORPATH\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
 7 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 8 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-27 22:43:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-11-27 22:43:08 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `users`.`deleted_at` IS NULL
AND `users`.`id` = :users.id:', [...], false)
 3 SYSTEMPATH\Model.php(182): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '3')
 5 VENDORPATH\myth\auth\src\Authentication\AuthenticationBase.php(130): CodeIgniter\BaseModel->find('3')
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(67): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
 7 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 8 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-27 23:03:33 --> Undefined variable: title
in APPPATH\Views\templates\index.php on line 6.
 1 APPPATH\Views\templates\index.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: title', 'APPPATH\\Views\\templates\\index.php', 6, [])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('templates/index', [], true)
 5 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('crud/datakosong', [], true)
 6 APPPATH\Controllers\Admin.php(45): view('crud/datakosong')
 7 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Admin->detail('100')
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
